apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: trigger-template
  namespace: arthur-vardevanyan
spec:
  params:
    - name: git-url
    - name: git-name
    - name: git-commit
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: "arthur-vardevanyan-"
      spec:
        serviceAccountName: pipeline-sa
        timeout: 15m0s
        pipelineRef:
          name: arthur-vardevanyan
        workspaces:
          - name: data
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 100Mi
                storageClassName: longhorn-single
                volumeMode: Filesystem
        params:
          - name: git-url
            value: $(tt.params.git-url)
          - name: git-name
            value: $(tt.params.git-name)
          - name: git-commit
            value: $(tt.params.git-commit)
          - name: IMAGE
            value: registry.<path:secret/data/homelab/domain#url>/apps/arthur-vardevanyan:$(tt.params.git-commit)
