apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arthurvardevanyan-ci
  namespace: arthurvardevanyan-ci
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    notifications.argoproj.io/subscribe.on-sync-succeeded.gh-tenant: ""
    notifications.argoproj.io/subscribe.on-sync-failed.gh-tenant: ""
    notifications.argoproj.io/subscribe.on-sync-status-unknown.gh-tenant: ""
    notifications.argoproj.io/subscribe.on-health-degraded.gh-tenant: ""
spec:
  destination:
    namespace: arthurvardevanyan-ci
    server: https://kubernetes.default.svc
  project: arthurvardevanyan-com
  source:
    path: tekton
    repoURL: https://git.arthurvardevanyan.com/ArthurVardevanyan/ArthurVardevanyan-com.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd
  namespace: arthurvardevanyan-ci
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: argocd-apps-argocd-application-controller
    namespace: argocd-apps
