---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gcp-credentials-request
  namespace: arthurvardevanyan-ci
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: gcp-credentials-request
    template:
      engineVersion: v2
      data:
        credentials_config.json: |
          {
              "type": "external_account",
              "audience": "//iam.googleapis.com/projects/{{ .homelab_project_num }}/locations/global/workloadIdentityPools/okd-homelab-wif/providers/okd-homelab-wif",
              "subject_token_type": "urn:ietf:params:oauth:token-type:jwt",
              "token_url": "https://sts.googleapis.com/v1/token",
              "service_account_impersonation_url": "https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/tekton@{{ .project_id }}.iam.gserviceaccount.com:generateAccessToken",
              "credential_source": {
                "file": "/var/run/secrets/openshift/serviceaccount/token",
                "format": {
                    "type": "text"
                }
            }
          }
  data:
    - secretKey: homelab_project_num
      remoteRef: # checkov:skip=CKV_SECRET_6 PlaceHolder Values
        conversionStrategy: Default
        decodingStrategy: None
        key: secret/data/gcp/org/av/folders/homelab
        property: homelab_project_num
        metadataPolicy: None
    - secretKey: project_id
      remoteRef: # checkov:skip=CKV_SECRET_6 PlaceHolder Values
        conversionStrategy: Default
        decodingStrategy: None
        key: secret/data/gcp/project/av
        property: project_id
        metadataPolicy: None
