apiVersion: v1
kind: LimitRange
metadata:
  name: default
  namespace: arthurvardevanyan-ci
spec:
  limits:
    - type: Container
      default:
        cpu: "100m"
        memory: 128Mi
        ephemeral-storage: 256Mi
      defaultRequest:
        cpu: 10m
        memory: 64Mi
        ephemeral-storage: 128Mi
