kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cache
  namespace: arthurvardevanyan-ci
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: rook-cephfs-ci
  volumeMode: Filesystem
