apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-deploy-rb
  namespace: arthur-vardevanyan
  labels:
    app.kubernetes.io/instance: arthur-vardevanyan
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: pipeline-sa
    namespace: arthur-vardevanyan
