apiVersion: apps/v1
kind: Deployment
metadata:
  name: arthur-vardevanyan
  namespace: arthur-vardevanyan
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: arthur-vardevanyan
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: arthur-vardevanyan
      annotations:
        enable.version-checker.io/arthur-vardevanyan: "false"
    spec:
      containers:
        - image: registry.<path:secret/data/homelab/domain#url>/apps/arthur-vardevanyan:<VERSION>
          imagePullPolicy: IfNotPresent
          name: arthur-vardevanyan
          env:
            - name: RECAPTCHA_SECRET
              valueFrom:
                secretKeyRef:
                  key: RECAPTCHA_SECRET
                  name: env
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "50M"
              cpu: "25m"
            limits:
              memory: "75M"
              cpu: "50m"
      hostname: arthur-vardevanyan
      restartPolicy: Always
