apiVersion: apps/v1
kind: Deployment
metadata:
  name: arthur-vardevanyan
  namespace: arthur-vardevanyan
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: arthur-vardevanyan
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: arthur-vardevanyan
      annotations:
        enable.version-checker.io/arthur-vardevanyan: "false"
    spec:
      containers:
        - image: registry.<path:secret/data/homelab/domain#url>/apps/arthur-vardevanyan:<VERSION>
          imagePullPolicy: IfNotPresent
          name: arthur-vardevanyan
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            privileged: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - all
          env:
            - name: RECAPTCHA_SECRET
              valueFrom:
                secretKeyRef:
                  key: RECAPTCHA_SECRET
                  name: env
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "50M"
              cpu: "25m"
            limits:
              memory: "75M"
              cpu: "50m"
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      hostname: arthur-vardevanyan
      restartPolicy: Always
      automountServiceAccountToken: false
      volumes:
        - name: tmp
          emptyDir:
            sizeLimit: 1Mi
