apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - ./namespace.yaml # Cluster Scoped, Skipped for Tenant Argo
  - ./secret.yaml
  - ./service.yaml
  - ./deployment.yaml
  - ./hpa.yaml
  - ./pdb.yaml
  - ./network-policy.yaml
