apiVersion: v1
kind: LimitRange
metadata:
  name: arthur-vardevanyan
  namespace: arthur-vardevanyan
  labels:
    app.kubernetes.io/instance: arthur-vardevanyan
spec:
  limits:
    - default:
        cpu: 100m
        memory: 100Mi
      defaultRequest:
        cpu: 50m
        memory: 50Mi
      type: Container
