apiVersion: v1
kind: LimitRange
metadata:
  name: <PROJECT>
  namespace: <PROJECT>
  labels:
    app.kubernetes.io/instance: <PROJECT>
spec:
  limits:
    - default:
        cpu: 200m
        memory: 250M
      defaultRequest:
        cpu: 100m
        memory: 200M
      type: Container
