apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: arthurvardevanyan
  namespace: arthurvardevanyan-com
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: arthurvardevanyan
