apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: arthurvardevanyan-admin
  namespace: arthurvardevanyan-com
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs:
      [
        "create",
        "delete",
        "deletecollection",
        "get",
        "list",
        "patch",
        "update",
        "watch",
      ]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs:
      [
        "create",
        "delete",
        "deletecollection",
        "get",
        "list",
        "patch",
        "update",
        "watch",
      ]
  - apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies"]
    verbs:
      [
        "create",
        "delete",
        "deletecollection",
        "get",
        "list",
        "patch",
        "update",
        "watch",
      ]
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs:
      [
        "create",
        "delete",
        "deletecollection",
        "get",
        "list",
        "patch",
        "update",
        "watch",
      ]
  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs:
      [
        "create",
        "delete",
        "deletecollection",
        "get",
        "list",
        "patch",
        "update",
        "watch",
      ]
  - apiGroups: ["external-secrets.io"]
    resources: ["externalsecrets"]
    verbs:
      [
        "create",
        "delete",
        "deletecollection",
        "get",
        "list",
        "patch",
        "update",
        "watch",
      ]
  - apiGroups: ["k8s.ovn.org"]
    resources: ["egressfirewalls"]
    verbs:
      [
        "create",
        "delete",
        "deletecollection",
        "get",
        "list",
        "patch",
        "update",
        "watch",
      ]
  - apiGroups: ["gateway.networking.k8s.io"]
    resources: ["httproutes"]
    verbs:
      [
        "create",
        "delete",
        "deletecollection",
        "get",
        "list",
        "patch",
        "update",
        "watch",
      ]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings"]
    verbs:
      [
        "create",
        "delete",
        "deletecollection",
        "get",
        "list",
        "patch",
        "update",
        "watch",
      ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openshift-pipelines-admin
  namespace: arthurvardevanyan-com
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: arthurvardevanyan-ci
  - kind: ServiceAccount
    name: pipeline
    namespace: arthurvardevanyan-com
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: arthurvardevanyan-admin
