apiVersion: v1
kind: ResourceQuota
metadata:
  name: <PROJECT>
  namespace: <PROJECT>
  labels:
    app.kubernetes.io/instance: <PROJECT>
spec:
  hard:
    requests.cpu: 150m
    requests.memory: 100M
    limits.cpu: 300m
    limits.memory: 200M
    services.nodeports: "0"
    services.loadbalancers: "0"
    requests.storage: "0"
    requests.ephemeral-storage: "0"
    limits.ephemeral-storage: "0"
