apiVersion: v1
kind: Secret
metadata:
  name: env
  namespace: arthur-vardevanyan
  labels:
    app.kubernetes.io/instance: arthur-vardevanyan
stringData:
  RECAPTCHA_SECRET: "<path:secret/data/arthur_vardevanyan#recaptcha_secret>"
