---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: env
  namespace: arthurvardevanyan-com
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: env
  data:
    - secretKey: RECAPTCHA_SECRET_KEY
      remoteRef: # checkov:skip=CKV_SECRET_6 PlaceHolder Values
        conversionStrategy: Default
        decodingStrategy: None
        key: secret/data/arthur_vardevanyan
        property: recaptcha_secret
        metadataPolicy: None
    - secretKey: SMTP_HOST
      remoteRef: # checkov:skip=CKV_SECRET_6 PlaceHolder Values
        conversionStrategy: Default
        decodingStrategy: None
        key: secret/data/smtp
        property: host
        metadataPolicy: None
    - secretKey: SMTP_FROM
      remoteRef: # checkov:skip=CKV_SECRET_6 PlaceHolder Values
        conversionStrategy: Default
        decodingStrategy: None
        key: secret/data/smtp
        property: username
        metadataPolicy: None
    - secretKey: SMTP_PASSWORD
      remoteRef: # checkov:skip=CKV_SECRET_6 PlaceHolder Values
        conversionStrategy: Default
        decodingStrategy: None
        key: secret/data/smtp
        property: password
        metadataPolicy: None
