apiVersion: v1
kind: Service
metadata:
  name: <PROJECT>
  namespace: <PROJECT>
  labels:
    app.kubernetes.io/instance: <PROJECT>
spec:
  selector:
    app: <PROJECT>
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
