apiVersion: v1
kind: Service
metadata:
  name: arthur-vardevanyan
  namespace: arthur-vardevanyan
  labels:
    app.kubernetes.io/instance: arthur-vardevanyan
spec:
  selector:
    app: arthur-vardevanyan
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
