apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: arthur-vardevanyan
  namespace: arthur-vardevanyan
  labels:
    app.kubernetes.io/instance: arthur-vardevanyan
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`<URL>`)
      kind: Rule
      services:
        - name: arthur-vardevanyan
          port: 8080
